General:
    comment: msunet, efficientnetb5, newkfold, no black and rotate, simple, more img size, add
    workdir: ../output/model/model049
    seed: 42
    fp16: True
    amp_level: O2
    multi_gpu_mode: ddp
    labels: [Fish, Flower, Gravel, Sugar]
    gpus: [0, 1, 2, 3]
    epoch: 30
    debug: False
    grad_acc: 4

Data:
    dataset:
        background_class: True
        train_df: ../input/train_5kfold.csv
        train_img_dir: ../input/train_images
        test_df: ../input/sample_submission.csv
        test_img_dir: ../input/test_images
        img_height: 512
        img_width: 768
        kfold: -1
    dataloader:
        batch_size: 16
        num_workers: 8
        train:
            use_sampler: True
            change_rate_sampler: False
            max_pos_rate: 1.0
        valid:
            use_sampler: False
        test:
            use_sampler: False

Model:
    encoder: efficientnet-b5
    model_arch: msunet
    in_channel: 3
    out_channel: 4
    pretrained: True
    use_aspp: True
    base_ch: 32
    decoder:
        attention: cbam
    hypercolumn: True
    output: sigmoid

Optimizer:
    optimizer: Adam
    init_lr: !!python/float 1e-3
    lr_scheduler:
        name: CosineAnnealingLR
        params:
            T_max: 30
            eta_min: !!python/float 5e-5
            last_epoch: -1

Loss:
    base_loss:
        name: BCEDiceFocalLoss
        params:
            r_d: 1.
            r_b: 0.5
            r_f: 1.
            softmax: False
    wrapper_loss:
        - name: DiceScoreL2LossWrapper
          params:
              alpha: 0.2

Augmentation:
    tta: [hflip, vflip]
    train:
        - name: HorizontalFlip
          params:
              p: 0.5
        - name: VerticalFlip
          params:
              p: 0.5
        - name: OneOf
          member:
              - name: RandomInputBlackEllipse
                params:
                    sl: 0.02
                    sh: 0.06
                    r1: 0.3
                    r2: !!python/object/apply:eval [ '1 / 0.3' ]
                    max_angle: 180
                    img_h: 1400
                    img_w: 2100
              - name: RandomInputBlack
                params:
                    sl: 0.01
                    sh: 0.1
                    r1: 0.3
                    r2: !!python/object/apply:eval [ '1 / 0.3' ]
                    img_h: 1400
                    img_w: 2100
          params:
              p: 0.5
        - name: RandomSizedCrop
          params:
              min_max_height: !!python/object/apply:eval [ '(int(1400 * 0.8), 1400)' ]
              height: 1400
              width: 2100
              # w2h_ratio = width / height
              w2h_ratio: !!python/object/apply:eval [ '2100 / 1400' ]
              interpolation: 1
              p: 0.5
        - name: ShiftScaleRotate
          params:
              scale_limit: 0.5
              rotate_limit: 0
              shift_limit: 0.1
              border_mode: 0
              p: 0.5
        - name: OneOf
          member:
              - name: GridDistortion
                params:
                    p: 1.
              - name: OpticalDistortion
                params:
                    distort_limit: 2
                    shift_limit: 0.5
                    p: 1.
          params:
              p: 0.5
    valid:
